### ISSUE TITLE
many icons missing

### ISSUE THREAD

**Issue by chinkihamza** [clean/frino_icons#1]
how to get those icons mentioned in the website is there also another way to add them

**Comment by peengle** [comment]
Can you refine which icons are missing? At https://www.rafalfuczynski.com/frino/icons/ there is still version 1.0.1 with 394 icons and they should all be available in the package.

**Comment by chinkihamza** [comment]
i coudnt find different versions of facebook and of them on android studio, is there any other way to add them through there codes no worry just drawn them on illustrator,btw thanks for asking
